spring.application.name=peliculas

spring.config.import=optional:application-local.properties

omdb.api.url=${omdb.api.url}
omdb.api.key=${omdb.api.key}

spring.datasource.url=${spring.datasource.url}
spring.datasource.username=${spring.datasource.username}
spring.datasource.password=${spring.datasource.password}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

security.jwt.secret=${security.jwt.secret}
security.jwt.expiration=3600000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true